"""Initial migration with all tables

Revision ID: 26dd0b498b2e
Revises: 
Create Date: 2026-02-14 18:45:40.138789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26dd0b498b2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensurations', sa.Column('cou', sa.Float(), nullable=True, comment='Tour de cou en cm'))
    op.add_column('mensurations', sa.Column('epaules', sa.Float(), nullable=True, comment="Tour d'épaules en cm"))
    op.add_column('mensurations', sa.Column('poitrine', sa.Float(), nullable=True, comment='Tour de poitrine en cm'))
    op.add_column('mensurations', sa.Column('nombril', sa.Float(), nullable=True, comment='Tour de nombril en cm'))
    op.add_column('mensurations', sa.Column('hanches', sa.Float(), nullable=True, comment='Tour de hanches en cm'))
    op.add_column('mensurations', sa.Column('biceps_gauche', sa.Float(), nullable=True, comment='Tour de biceps gauche en cm'))
    op.add_column('mensurations', sa.Column('biceps_droit', sa.Float(), nullable=True, comment='Tour de biceps droit en cm'))
    op.add_column('mensurations', sa.Column('cuisse_gauche', sa.Float(), nullable=True, comment='Tour de cuisse gauche en cm'))
    op.add_column('mensurations', sa.Column('cuisse_droite', sa.Float(), nullable=True, comment='Tour de cuisse droite en cm'))
    op.add_column('mensurations', sa.Column('mollet_gauche', sa.Float(), nullable=True, comment='Tour de mollet gauche en cm'))
    op.add_column('mensurations', sa.Column('mollet_droit', sa.Float(), nullable=True, comment='Tour de mollet droit en cm'))
    op.drop_column('mensurations', 'cuisses')
    op.drop_column('mensurations', 'bras')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensurations', sa.Column('bras', sa.FLOAT(), nullable=True))
    op.add_column('mensurations', sa.Column('cuisses', sa.FLOAT(), nullable=True))
    op.drop_column('mensurations', 'mollet_droit')
    op.drop_column('mensurations', 'mollet_gauche')
    op.drop_column('mensurations', 'cuisse_droite')
    op.drop_column('mensurations', 'cuisse_gauche')
    op.drop_column('mensurations', 'biceps_droit')
    op.drop_column('mensurations', 'biceps_gauche')
    op.drop_column('mensurations', 'hanches')
    op.drop_column('mensurations', 'nombril')
    op.drop_column('mensurations', 'poitrine')
    op.drop_column('mensurations', 'epaules')
    op.drop_column('mensurations', 'cou')
    # ### end Alembic commands ###
